version: "3"

includes:
  common:
    taskfile: ./common/Taskfile.yaml
    dir: ./common
  postgres:
    taskfile: ./postgres/Taskfile.yaml
    dir: ./postgres
  python-api:
    taskfile: ./python-api/Taskfile.yml
    dir: ./python-api