version: "3"

vars:
  IMAGE_REPO: ciaa/python-api
  IMAGE_TAG: mypassword

tasks:

  apply:
    desc: Deploy the python api
    cmds:
      - kubectl apply -f manifests

  delete:
    desc: Removes the api deployment
    cmds:
      - kubectl delete -f manifests

  build-container-image:
    desc: Build container image
    cmds:
      - docker build -t {{.IMAGE_REPO}}:{{.IMAGE_TAG}} .
  
  push-container-image:
    desc: Push recently built container image
    cmds:
      - docker push {{.IMAGE_REPO}}:{{.IMAGE_TAG}}

  build-container-image-multi-arch:
    desc: Build multi-arch container image (assuming that a build instance is availabe)
    cmds:
      - |
        docker buildx build \
        --platform linux/amd64,linux/arm64 \
        -t {{.IMAGE_REPO}}:{{.IMAGE_TAG}} \
        --push \
        .