apiVersion: v1
kind: Secret
metadata:
  name: db-password
  namespace: app
type: Opaque
stringData:
  DATABASE_URL: postgres://postgres:mypassword@postgres-postgresql.postgres.svc.cluster.local:5432/postgres