version: "3"

tasks:
  apply-namespace:
    desc: Apply Kubernetes Namespace
    cmds:
      - kubectl apply -f namespace.yml
      - kubens app

  deploy-nginx:
    desc: Deploy Nginx controller using helm
    cmds:
      - |
        helm upgrade --install ingress-nginx ingress-nginx \
          --repo https://kubernetes.github.io/ingress-nginx \
          --namespace ingress-nginx \
          --create-namespace \
          --version 4.10.1
  
  delete-nginx:
    desc: Uninstall Nginx controller using helm
    cmds:
      - |
        helm uninstall -n ingress-nginx ingress-nginx

  deploy-ingress-nginx:
    desc: Deploy ingress with Nginx controller
    cmds:
      - |
        kubectl apply -f ingress.yml

  delete-ingress-nginx:
    desc: Delete ingress with Nginx controller
    cmds:
      - |
        kubectl delete -f ingress.yml