version: "3"

tasks:
  generate-version-tag:
    cmds:
      - cmd: git describe --tags --always --first-parent --match "[0-9]*.[0-9]*.[0-9]*"
        silent: true
    desc: "Use git describe to generate a tag based on the latest release tag"

  check-new-tag-var:
    desc: "Check if NEW_TAG variable is set"
    cmds:
      - cmd: |
          if [ -z "{{.NEW_TAG}}" ] ; then
            echo "NEW_TAG var is required" && exit 1;
          fi

  update-image-tags:
    desc: "Recursively update image tags in files with the specified comment"
    vars:
      EXCLUDED_FILES: |
        {{.TASKFILE_DIR}}/Taskfile.yml
      IDENTIFIER_COMMENT: "# LATEST_IMAGE_TAG"
      STARTING_PATH:
            sh: git rev-parse --show-toplevel
    cmds:
      - task: check-new-tag-var
      - cmd: |
          echo "STARTING_PATH: {{ .STARTING_PATH }}"
          echo "IDENTIFIER_COMMENT: {{ .IDENTIFIER_COMMENT }}"
          echo "NEW_TAG: {{ .NEW_TAG }}"
        silent: true
      - cmd: |
          find "{{.STARTING_PATH}}" -type f \( -name "*.yml" \) -exec grep -l "{{ .IDENTIFIER_COMMENT }}" {} \; | while read -r file; do
            if ! echo "{{ .EXCLUDED_FILES }}" | grep -q "$file"; then
              echo "Updating: $file"
              sed -i "s|\(\s*.*:\s*\).* \({{ .IDENTIFIER_COMMENT }}\)|\1{{ .NEW_TAG }} \2|" "$file";
            fi
          done