apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-api
  namespace: app
  labels:
    app: python-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-api
  template:
    metadata:
      labels:
        app: python-api
    spec:
      containers:
        - name: python-api
          image: docker.io/ciaa/python-api:mypassword
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: python-api-database-url
          ports:
            - name: readiness-port 
              containerPort: 8000
          readinessProbe:
            httpGet:
              path: /healthz
              port: readiness-port 
          startupProbe:
            httpGet:
              path: /healthz
              port: readiness-port 
            failureThreshold: 5
            periodSeconds: 2          
          resources:
            limits:
              memory: "4000Mi"
            requests:
              memory: "4000Mi"
              cpu: "2000m"
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault