name: image-ci
on:
  push:
    branches:
      - "master"
    tags:
      - "[0-9]*.[0-9]*.[0-9]*"
    paths:
      - "deploy/k8s/apps/**/*"
    paths-ignore:
      - "deploy/k8s/apps/**/manifests/deployment.yml"
jobs:
  generate-image-tag:
    runs-on: ubuntu-24.04
    outputs:
      image_tag: ${{ steps.generate-image-tag.outputs.image_tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x

      - name: Generate Image Tag
        id: generate-image-tag
        working-directory: cicd/github-actions
        run: |
          image_tag=$(task generate-version-tag)
          echo "image_tag=$image_tag" >> $GITHUB_OUTPUT
          echo "$image_tag"

  build-tag-push:
    runs-on: ubuntu-24.04
    needs: generate-image-tag
    strategy:
      matrix:
        path:
          - deploy/k8s/apps/python-api
          - deploy/k8s/apps/streamlit
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Dockerfile
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        env:
          IMAGE_TAG: ${{ needs.generate-image-tag.outputs.image_tag }}
        working-directory: ${{ matrix.path }}
        run: |
          task build-container-image-multi-arch IMAGE_TAG=${IMAGE_TAG}

  update-tags:
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-24.04
    needs: [generate-image-tag, build-tag-push]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x

      - name: Update Image Tags
        working-directory: cicd/github-actions
        env:
          IMAGE_TAG: ${{ needs.generate-image-tag.outputs.image_tag }}
        run: |
          task update-image-tags NEW_TAG=${IMAGE_TAG}            

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          base: master
          branch: new_image_tag
          delete-branch: true
          token: ${{ secrets.K8S_MICROSERVICE_FG_PAT }}
          title: "Update image tags to ${{ needs.generate-image-tag.outputs.image_tag }}"